ame: Sync

on: page_build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDmUmARBLO76SfqH9IfbQsO+IHhB47wFgE/pp+mABbgctpNIVgarqJ2Co0yPhktbTeo+X1C1be48+o3XQA6kbEqJkCCw0nSiHqaTR/rvzIl6tONHedeqA67sHXEXQ5fyF5uox4UapkTlDG9FoAbugn3xlNCzPnFmX6bSEF1VEB/DeMYpAawYLgE2ScCxfUn/dh05BwMpRfOSXVgIPfUhSMYz7/n6fA0SgT8jg8AStMuFc21WjV4tusUFUrSAjtQmu97JY41QMbzygJZDzB/zOwKhcV0uN/qHz4429G5e2qzVjvN5ONbAzUTv9Wr2yfn1cGLBfA3pzlGGctvPVtgA3pfj7k570Lmlr/8GyhtejFSS6nJlwJnwk1Ov/XkDHjRh0U7fm6IlRCtY8WI2SLxALt3VuUqOZEwbNzzVdgAGOgkQzMSr82xA13kFJhoL+greUEXu4g2NS82BQKp+6wKBZ3ablqrwtuxc7OUEduFVjwxTIffqWKD1Oo3yxA4jNvvHieuQLsaaONv2BXi0kjm8c/Lg6q6UnvAtoWE8DMJ5kAq1Mpvz142167pNijDVaZvvnAcb5g/rvgmpcAR/T8HXw/qB3z2rvPe3/hh/6dimNY2kQ2sph4xoBbYntVAdejxj1nBlONDvTXkP2pSBloBnYBvaImpsCoDH8NzcZHZK4jJbQ== 3238856289@qq.com
 }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:weimeng1/weimeng1.github.io.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: https://gitee.com/jxxg/jxxg.git
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: jxxg
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{CDX159357}}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: https://gitee.com/jxxg/jxxg.git
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: master
